<%-- 
    Document   : welcome
    Created on : 26 Jun, 2017, 10:56:00 PM
    Author     : Pallab Ganguly
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Welcome!</title>
    </head>
    <body>
        <h1>Welcome!</h1>
        <p>The time now is: 
            <%
                System.out.println("Generated by scriptlet! Nothing New");
                java.util.Date date = new java.util.Date();
                //generate HTML output
                out.println(date.toString());
            %>
        </p>
        <p>
            <%
                out.println("Your IP Address is" + request.getRemoteHost());
            %>
        </p>
    </body>
</html>
